name: hw1_env
dependencies: 
  - python=3.7
  - pip
  - pip: 
    - matplotlib==3.4.1
    - numpy==1.20.1
    - pandas==1.2.2
    - scikit-learn==0.24.2
    - seaborn==0.9.0
    - lightgbm==3.2.1
    - catboost==0.25.1
